### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by sash19** [apptainer/apptainer#2361]
### Version of Apptainer

`apptainer version 1.3.1`

### Expected behavior

Run smoothly without any issues. 

### Actual behavior

I get an OSError saying Transport endpoint not connected when an application inside the container is launched through python's subprocess library as a dask task. 

`2024-07-15 11:26:17,378 - tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x2b31c1903e20>>, <Task finished name='Task-2812' coro=<SpecCluster._correct_state_internal() done, defined at /usr/local/lib/python3.10/dist-packages/distributed/deploy/spec.py:346> exception=OSError(107, 'Transport endpoint is not connected')>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 750, in _run_callback
  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 774, in _discard_future_result
  File "/usr/local/lib/python3.10/dist-packages/distributed/deploy/spec.py", line 390, in _correct_state_internal
  File "/usr/lib/python3.10/asyncio/tasks.py", line 650, in _wrap_awaitable
  File "/usr/local/lib/python3.10/dist-packages/distributed/deploy/spec.py", line 74, in _
  File "/usr/local/lib/python3.10/dist-packages/scalable/slurm.py", line 93, in start
  File "/usr/local/lib/python3.10/dist-packages/scalable/core.py", line 299, in _run_command
  File "/usr/local/lib/python3.10/dist-packages/scalable/core.py", line 375, in _call
  File "/usr/local/lib/python3.10/dist-packages/scalable/utilities.py", line 42, in get_cmd_comm
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1681, in subprocess_exec
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 799, in _start
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
OSError: [Errno 107] Transport endpoint is not connected: './communicator'`

"communicator" is a server I wrote for the container to contact the host. Once this error occurs, nothing can be ran through subprocess. Everything gives the same error. Running a command like `subprocess.run("ls", stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)` gives the same error replacing communicator with "/bin/sh". If I run it with shell=False then the same error with communicator replaced with "ls". 

Moreover, once this error has occurred, attempting to open any existing file or creating a new file in the python instance causes the container to crash ("core dumped" error). It seems like the container can't access its filesystem.

### Steps to reproduce this behavior

This problem is intermittent. It happens more or less randomly. The same code which would run perfectly most times would error out somewhere in the middle with an OSError out of nowhere. And once it errors out, like I mentioned above, it becomes unusable. While I'm not completely sure about this, I do think that I didn't see this problem before apptainer version 1.3.0. 

### What OS/distro are you running

`PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy`

### How did you install Apptainer

I'm using apptainer on my organization's HPC. I just do `module load apptainer/1.3.1`.

**Comment by sash19** [comment]
> You haven't given us nearly sufficient information for us to help identify the problem. It's not at all clear that it's an apptainer problem vs. an application problem.

Could you tell me what other information could be helpful? Since the issue is intermittent and seems like a filesystem access error, I'm pretty sure it is apptainer here. There isn't a very easy way to replicate this reliably but when I use a command like `apptainer exec --userns ~/containers/scalable_container.sif python3` to run python3, this error sometimes shows up right away as I start getting it on import statements. It doesn't always fail at the same or even similar places. I was wondering if anyone has seen something similar too.

**Comment by DrDaveD** [comment]
For starters you could say how to get a copy of your sif file, preferably via a definition file to rebuild it.  The full command line is important, which you now gave.

I haven't heard of anybody else reporting a similar problem.

**Comment by sash19** [comment]
Got it, my project does have a lot of moving parts so I'm going to try to design a container and a small isolated piece of code which can replicate this issue, at least in an intermittent manner, given I have an idea of what my project is doing. I'll get back to you after, thanks!

**Comment by sash19** [comment]
Hello, while I don't have exactly a simple way of making the container to replicate this problem. I do have a question. It seems like my problem is occurring because the `squashfuse_ll` process just randomly dies. Sometimes when this happens, this log INFO gets printed:

`INFO:    Terminating squashfuse_ll after timeout`
`INFO:    Timeouts can be caused by a running background process`

Could you please tell me what exactly happened here? What does this mean by a "running background process"? I have a lot of running background processes which shouldn't interfere with it. The `squashfuse_ll` seems to be a particularly weird process, it can die randomly (causing all kinds of other problems) or die with a SIGINT on exit. If you can elaborate on what exactly was your idea behind this message then that would be very helpful. Thanks!

**Comment by DrDaveD** [comment]
Those messages come during shut down, so they're unlikely to be the root cause of your problem, they're probably a side effect.

During shutdown, apptainer unmounts the fuse filesystem, and normally that causes the fuse program behind it to exit, but if some process still has something open on that filesystem, the fuse program will hang around.  If that goes on for a period of time, apptainer kills the fuse program.  The message talks about a background process because normally apptainer exits when the primary process exits.  If the process forked and the process in the background is still running at exit time, it can cause those messages.

**Comment by sash19** [comment]
Okay, that makes sense. I'll investigate further and circle back. The `squashfuse_ll` process often dies before I try to quit too but this message only happens when my dask cluster doesn't close properly so it's possible it has something open in the background. This makes sense. I'm now trying to figure out a way of reliably replicating the issue or the cause in my code for the process dying. Thanks!
