### ISSUE TITLE
segmentation fault when running alpine-glibc container on almalinux 9 host

### ISSUE THREAD

**Issue by vincent-pollet** [apptainer/apptainer#2533]
### Version of Apptainer
```bash
$ apptainer --version
apptainer version 1.3.3-1.el9
```

### Expected behavior

`apptainer run` or `apptainer shell` to start the `alpine-glibc` container without error.

### Actual behavior
`apptainer shell` or `apptainer run`  crashes with a segmentation fault when running on AlmaLinux 9 host.

### Steps to reproduce this behavior

Initially, I ran into the issue by using the [`frolvlad/alpine-glibc`](https://hub.docker.com/r/frolvlad/alpine-glibc/) container on an AlmaLinux 9 host. On such a host, the problem can be simply reproduced with:
```sh
$ apptainer pull docker://frolvlad/alpine-glibc                                         
INFO:    Converting OCI blobs to SIF format                                                                        
INFO:    Starting build...                                                                                         
Copying blob 0ef8aae03cbc done   |                                                                                 
Copying blob 43c4264eed91 skipped: already exists                                                                  
Copying config ba43bebdb2 done   |                                                                                 
Writing manifest to image destination                                                                              
2024/10/01 13:58:16  info unpack layer: sha256:43c4264eed91be63b206e17d93e75256a6097070ce643c5e8f0379998b44f170    
2024/10/01 13:58:16  info unpack layer: sha256:0ef8aae03cbc0ee87e5d55bff24220af3d71a7c0a4cd5b6ff098db50c8f3191a    
INFO:    Creating SIF file...

$ apptainer run alpine-glibc_latest.sif                                                 
SIGSEGV: segmentation violation                                                                                    
PC=0x4c0d0 m=0 sigcode=1                                                                                           
signal arrived during cgo execution                                                                                
                                                                                                                   
goroutine 1 [syscall, locked to thread]:                                                                           
runtime.cgocall(0x56109b264300, 0xc00025fdd8)                                                                      
        runtime/cgocall.go:157 +0x4b fp=0xc00025fdb0 sp=0xc00025fd78 pc=0x56109abff4eb                             
vendor/github.com/golang-fips/openssl-fips/openssl._Cfunc__goboringcrypto_DLOPEN_OPENSSL()
        _cgo_gotypes.go:349 +0x4c fp=0xc00025fdd8 sp=0xc00025fdb0 pc=0x56109ae5310c
vendor/github.com/golang-fips/openssl-fips/openssl.init.0()
        vendor/github.com/golang-fips/openssl-fips/openssl/openssl.go:68 +0xcb fp=0xc00025fe10 sp=0xc00025fdd8 pc=0x56109ae6210b
runtime.doInit1(0x56109b95d000)
        runtime/proc.go:6735 +0xda fp=0xc00025ff40 sp=0xc00025fe10 pc=0x56109ac44fda
runtime.doInit(...)
        runtime/proc.go:6702 
runtime.main()
        runtime/proc.go:249 +0x397 fp=0xc00025ffe0 sp=0xc00025ff40 pc=0x56109ac37c57
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc00025ffe8 sp=0xc00025ffe0 pc=0x56109ac690c1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc00004cfa8 sp=0xc00004cf88 pc=0x56109ac37fee
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.forcegchelper()
        runtime/proc.go:322 +0xb8 fp=0xc00004cfe0 sp=0xc00004cfa8 pc=0x56109ac37e78
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x56109ac690c1
created by runtime.init.6 in goroutine 1
        runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc00004d778 sp=0xc00004d758 pc=0x56109ac37fee
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.bgsweep(0x0?)
        runtime/mgcsweep.go:280 +0x94 fp=0xc00004d7c8 sp=0xc00004d778 pc=0x56109ac21194
runtime.gcenable.func1()
        runtime/mgc.go:200 +0x25 fp=0xc00004d7e0 sp=0xc00004d7c8 pc=0x56109ac160a5
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc00004d7e8 sp=0xc00004d7e0 pc=0x56109ac690c1
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000076000?, 0x56109b374a98?, 0x1?, 0x0?, 0xc0000071e0?)
        runtime/proc.go:398 +0xce fp=0xc00004df70 sp=0xc00004df50 pc=0x56109ac37fee
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.(*scavengerState).park(0x56109b9a0100)
        runtime/mgcscavenge.go:425 +0x49 fp=0xc00004dfa0 sp=0xc00004df70 pc=0x56109ac1e849
runtime.bgscavenge(0x0?)
        runtime/mgcscavenge.go:653 +0x3c fp=0xc00004dfc8 sp=0xc00004dfa0 pc=0x56109ac1edfc
runtime.gcenable.func2()
        runtime/mgc.go:201 +0x25 fp=0xc00004dfe0 sp=0xc00004dfc8 pc=0x56109ac16045
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc00004dfe8 sp=0xc00004dfe0 pc=0x56109ac690c1
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:201 +0xa5

goroutine 5 [finalizer wait]:
runtime.gopark(0x198?, 0x56109b4f4e60?, 0x1?, 0x91?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc00004c620 sp=0xc00004c600 pc=0x56109ac37fee
runtime.runfinq()
        runtime/mfinal.go:193 +0x107 fp=0xc00004c7e0 sp=0xc00004c620 pc=0x56109ac15047
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc00004c7e8 sp=0xc00004c7e0 pc=0x56109ac690c1
created by runtime.createfing in goroutine 1
        runtime/mfinal.go:163 +0x3d

rax    0x7f176f79c550
rbx    0x7f176f79c558
rcx    0x7f176f7f88a0
rdx    0x7ffc4f5530b8
rdi    0x1
rsi    0x7ffc4f5530a8
rbp    0x1
rsp    0x7ffc4f5528e8
r8     0x56109c6f4e20
r9     0xfffa320300000000
r10    0x478bfbff
r11    0xd
r12    0x7ffc4f5530a8
r13    0x7ffc4f5530b8
r14    0x7f176f79c558
r15    0x0
rip    0x4c0d0
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0
```
The AlmaLinux 9 os is:
```sh
$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="9.4 (Seafoam Ocelot)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.4 (Seafoam Ocelot)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
SUPPORT_END=2032-06-01
```
The AlmaLinux host is a server machine for which I don't have administrator privilege, and I didn't have another AlmaLinux 9 to use as a host to reproduce. However, the issue happens as well when running apptainer from inside an AlmaLinux 9 container. The following can be used to reproduce the issue for instance on an ubuntu laptop:

```sh
# Build an almalinux 9 container with apptainer 
$ cat almalinux.def 
Bootstrap: docker
From: almalinux:9

%post
  dnf install -y epel-release
  dnf install -y apptainer

$ apptainer build almalinux.sif almalinux.def

# Pull the alpine-glibc image:
$ apptainer pull docker://frolvlad/alpine-glibc

# Start the almalinux 9 container
$ apptainer shell -B $(pwd):$(pwd) almalinux.sif

# From inside this container: use apptainer 1.3.4-1.el9 with the alpine-glibc image:
Apptainer> apptainer shell alpine-glibc_latest.sif
# Segmentation fault error as if running the alpine-glibc directly on a AlmaLinux 9 host
```

### How did you install Apptainer

Apptainer was installed with `dnf` on the AlmaLinux server, and with `apt` on my laptop. The administrator of the AlmaLinux server reproduced the issue with apptainer 1.3.4 and 1.3.2 as well.

-----------------------
@frol and @sgerrand I thought you might be interested in following this issue as the providers of the `alpine-glibc` container
@wholtz as well since the micromamba alpine image are based on the `alpine-glibc`.

**Comment by DrDaveD** [comment]
I can reproduce this on alma9, even when the sif file was pulled on rocky8.  I didn't get the nice stack dumps though.  It runs fine on rocky8.

It may be related to #2449.  It seems to happen in the garbage collector like that one.
